### ISSUE TITLE
Upgrading to Pyserini 0.24 means `.raw` option not available.

### ISSUE THREAD

**Issue by bevankoopman** [castorini/pyserini#1762]
Upgrading to pyserini 0.24 causes the following error:

```
File "/Users/.../service.py", line 44, in search
    hybrid_hits, sparse_raws = self.hybrid(dense_hits, sparse_hits, 0.7, k)
File "/Users/../service.py", line 85, in hybrid
    sparse_raws[hit.docid] = hit.raw
AttributeError: 'io.anserini.search.ScoredDoc' object has no attribute 'raw'
```
This works fine with Pyserini 0.22.

Seems the API has changed so raw attribute no longer exists? What should we use instead? (I note too that a lot of tutorial / code example seem to reference the use of this attribute.)

**Comment by lintool** [comment]
See discussion here: https://github.com/castorini/pyserini/pull/1758 for alternatives

I made this API change because, previously, the `Result` object would load the raw doc content eagerly. Instead it does so lazily.

Change to something like this?

```
hits[0].lucene_document.get('raw')
```

Closing... but please reopen if you have any other issues?
