### ISSUE TITLE
Bug: init_query_encoder() missing 1 required positional argument: 'multimodal'

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1830]
@justram I believe this was introduced by #1828

```
TypeError: init_query_encoder() missing 1 required positional argument: 'multimodal'
Traceback (most recent call last):
  File "/home/jimmylin/.conda/envs/pyserini-dev3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jimmylin/.conda/envs/pyserini-dev3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/store/scratch/jimmylin/pyserini/pyserini/search/hybrid/__main__.py", line 106, in <module>
    query_encoder = init_query_encoder(args.dense.encoder,
```

**Comment by justram** [comment]
issue fixed, tested with the following CLI & Python interface [test case](https://github.com/castorini/pyserini/blob/dcd2fe07f1840757e840d9eaeb54a1c4cc6755f7/tests/test_hybrid_search.py)
```shell
python -m pyserini.search.hybrid \
run --topics msmarco-passage-dev-subset \
      --output runs/run.fusion.trec \
      --batch-size 32 \
      --threads 16 \
dense --index msmarco-passage-tct_colbert-hnsw \
           --encoder castorini/tct_colbert-msmarco \
sparse --index msmarco-v1-passage \
fusion --hits 1000
```
