### ISSUE TITLE
Bug introduced by #1622 max_length in init_query_encoder

### ISSUE THREAD

**Issue by lintool** [castorini/pyserini#1699]
hi @jasper-xian I think you introduced this bug?

```
python -m pyserini.search.hybrid \
  dense  --index msmarco-v1-passage.tct_colbert-v2-hnp \
         --encoded-queries tct_colbert-v2-hnp-msmarco-passage-dev-subset \
  sparse --index msmarco-v1-passage-d2q-t5 \
  fusion --alpha 0.1 \
  run    --topics msmarco-passage-dev-subset \
         --output run.msmarco-passage.tct_colbert-v2-hnp.bf.doc2queryT5.tsv \
         --output-format msmarco \
         --batch-size 36 --threads 12
```

Error I'm getting:

```
Using pre-defined topic order for msmarco-passage-dev-subset
Traceback (most recent call last):
  File "/Users/jimmylin/anaconda3/envs/pyserini-dev3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/jimmylin/anaconda3/envs/pyserini-dev3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/jimmylin/workspace/pyserini/pyserini/search/hybrid/__main__.py", line 106, in <module>
    query_encoder = init_query_encoder(args.dense.encoder,
TypeError: init_query_encoder() missing 1 required positional argument: 'max_length'
```

**Comment by lintool** [comment]
Fixed.
